### ISSUE TITLE
Runs ok Locally but not on Ubuntu

### ISSUE THREAD

**Issue by dschinkel** [janpieterz/koajs-static-folder#5]
After deploying the following code to an Ubuntu server, the static asset no longer works.  I get an error when trying to run my app from Ubuntu:

2015-08-17T16:37:13.584321427Z Error: ENOENT, no such file or directory './assets'

var koa = require('koa')(),
serve = require('koa-static-folder');

koa.use(serve('./assets'));

**Comment by janpieterz** [comment]
Sorry to hear that, you're running the latest version I assume? It changed to use process.cwd() a while ago.
What is your local development OS?

Would you be up for investigating some things? I don't have an ubuntu ready/close to me.

**Comment by dschinkel** [comment]
Yea I'm troubleshooting it now.  I'm using Yosemite.  So it runs fine in the browser.  I'm in ubuntu now so running my koa app right now inside ubuntu (node --harmony app.js).  Sorry, what's about the process.cwd() again??

**Comment by janpieterz** [comment]
I use [process.cwd()](https://nodejs.org/api/process.html#process_process_cwd) to get the root of the application and then try to find the directory. In your case it can't find the directory, so something is going on there.

If you look in the packages folder and you find this package, the index.js file should be relatively easy to understand. Try placing some console writes to pinpoint where it goes wrong, what process.cwd returns etc! A good help can also be logging the var finalFiles since this will give you all the files that are handled with this library, you can get some location information from that.

Sorry I can't be of more help currently, I'm on holiday.

**Comment by dschinkel** [comment]
I am not using an index.js.  This is a REST API.

**Comment by dschinkel** [comment]
I will play with it.  Disregard my comment on index.js.  I'll check yours out as you had suggested...thanks!

**Comment by mfchung** [comment]
I've developing on Ubuntu 15.04, it seems to work fine...

**Comment by janpieterz** [comment]
@mfchung awesome, thanks for your feedback!

@dschinkel did you get anywhere?

**Comment by janpieterz** [comment]
I'll close this one for now. In case it happens again I'm more than willing to dive deeper into it.
